export const RETURN = {
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  NOT_FOUND: "NOT_FOUND",
  EMAIL_EXISTS: "EMAIL_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_NOT_ACTIVE: "USER_NOT_ACTIVE",
  MALFORMED_TOKEN: "MALFORMED_TOKEN",
  UNAUTHORIZED: "UNAUTHORIZED",
};
